### ISSUE TITLE
Need mirrolist refresh

### ISSUE THREAD

**Issue by DraGiuS** [NearHuscarl/arch_installer#1]
The mirrolist part (by speed) do not work.

**Comment by NearHuscarl** [comment]
I do a partial update, so its dependency also need to be updated as well. Reopen if you still encounter any issues

**Comment by DraGiuS** [comment]
Still don't work "no module named reflector"

**Comment by NearHuscarl** [comment]
Sorry about that, should have checked it in my virtualbox first. I have fixed and moved the configure mirror part into postinstall in the `dev` branch
